import { MigrationInterface, QueryRunner } from "typeorm";

export class NotificationEnumUpdates1780960970910 implements MigrationInterface {
    name = 'NotificationEnumUpdates1780960970910'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "user_settings" DROP CONSTRAINT "FK_user_settings_userId"`);
        await queryRunner.query(`ALTER TABLE "order_disputes" DROP CONSTRAINT "FK_77f99ec8e32921d9c29a468c4b6"`);
        await queryRunner.query(`ALTER TABLE "order_disputes" DROP CONSTRAINT "fk_order_disputes_resolved_by_id"`);
        await queryRunner.query(`ALTER TABLE "product_ratings" DROP CONSTRAINT "FK_538c9489e98d4874e8db0c4cafd"`);
        await queryRunner.query(`ALTER TABLE "product_ratings" DROP CONSTRAINT "FK_7f190f97558c87ec1c14a3d6378"`);
        await queryRunner.query(`ALTER TABLE "post_comments" DROP CONSTRAINT "FK_2b93091c2f4d6c9cf7c9b32e29f"`);
        await queryRunner.query(`ALTER TABLE "post_comments" DROP CONSTRAINT "FK_ac65d744abc05279aee0b290857"`);
        await queryRunner.query(`ALTER TABLE "post_likes" DROP CONSTRAINT "FK_37d337ad54b1aa6b9a44415a498"`);
        await queryRunner.query(`ALTER TABLE "post_likes" DROP CONSTRAINT "FK_6999d13aca25e33515210abaf16"`);
        await queryRunner.query(`ALTER TABLE "reports" DROP CONSTRAINT "FK_4353be8309ce86650def2f8572d"`);
        await queryRunner.query(`ALTER TABLE "posts" DROP CONSTRAINT "FK_c5a322ad12a7bf95460c958e80e"`);
        await queryRunner.query(`ALTER TABLE "follows" DROP CONSTRAINT "FK_666a44940ce8279976767c6b5e3"`);
        await queryRunner.query(`ALTER TABLE "follows" DROP CONSTRAINT "FK_fdb91868b03a2040db408a53331"`);
        await queryRunner.query(`ALTER TABLE "post_saves" DROP CONSTRAINT "FK_08107d1d38fc71d50702e1a8733"`);
        await queryRunner.query(`ALTER TABLE "post_saves" DROP CONSTRAINT "FK_15b357815f5e6a765e60ee0e32e"`);
        await queryRunner.query(`ALTER TABLE "post_shares" DROP CONSTRAINT "FK_15ea4c725c1f17facbc53b75e53"`);
        await queryRunner.query(`ALTER TABLE "post_shares" DROP CONSTRAINT "FK_95c8a0c593c2320addcc7af1468"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_692a909ee0fa9383e7859f9b406"`);
        await queryRunner.query(`ALTER TABLE "newsletter_sends" DROP CONSTRAINT "FK_newsletter_sends_sentBy"`);
        await queryRunner.query(`ALTER TABLE "announcements" DROP CONSTRAINT "FK_announcements_createdBy"`);
        await queryRunner.query(`DROP INDEX "public"."idx_seeker_profiles_seller_plan"`);
        await queryRunner.query(`DROP INDEX "public"."idx_shop_products_average_rating"`);
        await queryRunner.query(`DROP INDEX "public"."idx_shop_products_featured_until"`);
        await queryRunner.query(`DROP INDEX "public"."idx_shop_products_featured_search_vector"`);
        await queryRunner.query(`DROP INDEX "public"."idx_payment_audit_order"`);
        await queryRunner.query(`DROP INDEX "public"."idx_payment_audit_reference"`);
        await queryRunner.query(`DROP INDEX "public"."idx_payment_audit_gateway"`);
        await queryRunner.query(`DROP INDEX "public"."idx_payment_audit_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_payment_audit_created"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_538c9489e98d4874e8db0c4caf"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7f190f97558c87ec1c14a3d637"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_407d527627ceff1a5590eaba06"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_19d30f9d2260c7a9f1f55fa346"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fccf8ad12448a532feb8127280"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_65d5fbf616c25e628a12898e68"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_578cb9c4f13bcb6ac2710de410"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bc696393201e2083ea0db9d58d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_15ea4c725c1f17facbc53b75e5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_82c4b7dc16c5f5995ce6cf8592"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_692a909ee0fa9383e7859f9b40"`);
        await queryRunner.query(`ALTER TABLE "follows" DROP CONSTRAINT "UQ_63cae1eb7767feee4555f00c5f1"`);
        await queryRunner.query(`CREATE TABLE "saved_posts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "userId" uuid, "postId" uuid, CONSTRAINT "UQ_4d3790479b4ace0798f7d54c551" UNIQUE ("userId", "postId"), CONSTRAINT "PK_868375ca4f041a2337a1c1a6634" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b2b1d571903f71883bc942f2ed" ON "saved_posts" ("userId", "createdAt") `);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "issuspended"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "isdeleted"`);
        await queryRunner.query(`ALTER TABLE "shop_products" DROP COLUMN "averagerating"`);
        await queryRunner.query(`ALTER TABLE "shop_products" DROP COLUMN "totalratings"`);
        await queryRunner.query(`ALTER TABLE "shop_products" DROP COLUMN "ratingdistribution"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "confirmedat"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "autoconfirmscheduledat"`);
        await queryRunner.query(`ALTER TABLE "order_disputes" DROP COLUMN "resolutionNotes"`);
        await queryRunner.query(`ALTER TABLE "order_disputes" DROP COLUMN "resolvedAt"`);
        await queryRunner.query(`ALTER TABLE "order_disputes" DROP COLUMN "resolvedById"`);
        await queryRunner.query(`ALTER TABLE "product_ratings" DROP COLUMN "product_id"`);
        await queryRunner.query(`ALTER TABLE "product_ratings" DROP COLUMN "buyer_id"`);
        await queryRunner.query(`ALTER TABLE "product_ratings" DROP COLUMN "is_verified_purchase"`);
        await queryRunner.query(`ALTER TABLE "product_ratings" DROP COLUMN "order_id"`);
        await queryRunner.query(`ALTER TABLE "product_ratings" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "product_ratings" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "product_ratings" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "post_comments" DROP COLUMN "body"`);
        await queryRunner.query(`ALTER TABLE "post_likes" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "reports" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "reports" DROP COLUMN "targetType"`);
        await queryRunner.query(`DROP TYPE "public"."reports_targettype_enum"`);
        await queryRunner.query(`ALTER TABLE "reports" DROP COLUMN "targetId"`);
        await queryRunner.query(`ALTER TABLE "posts" DROP COLUMN "imageUrl"`);
        await queryRunner.query(`ALTER TABLE "follows" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "follows" DROP COLUMN "followeeId"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "product_ratings" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "product_ratings" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "product_ratings" ADD "isVerifiedPurchase" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "product_ratings" ADD "orderId" character varying`);
        await queryRunner.query(`ALTER TABLE "product_ratings" ADD "productId" uuid`);
        await queryRunner.query(`ALTER TABLE "product_ratings" ADD "buyerId" uuid`);
        await queryRunner.query(`ALTER TABLE "post_comments" ADD "content" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "reports" ADD "description" text`);
        await queryRunner.query(`CREATE TYPE "public"."reports_status_enum" AS ENUM('pending', 'reviewed', 'resolved')`);
        await queryRunner.query(`ALTER TABLE "reports" ADD "status" "public"."reports_status_enum" NOT NULL DEFAULT 'pending'`);
        await queryRunner.query(`ALTER TABLE "reports" ADD "reviewedAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "reports" ADD "reviewedBy" uuid`);
        await queryRunner.query(`ALTER TABLE "reports" ADD "postId" uuid`);
        await queryRunner.query(`ALTER TABLE "follows" ADD "acceptedAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "follows" ADD "followingId" uuid`);
        await queryRunner.query(`ALTER TABLE "post_likes" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "post_comments" ADD "body" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "follows" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "follows" ADD "followeeId" uuid`);
        await queryRunner.query(`ALTER TABLE "reports" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "reports" ADD "targetType" "public"."reports_targettype_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "reports" ADD "targetId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "employer_profiles" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "employer_profiles" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "employer_profiles" DROP CONSTRAINT "FK_9800cae27bdc0b9cbbc16e1556a"`);
        await queryRunner.query(`ALTER TABLE "legal_pages" DROP CONSTRAINT "FK_5addf284971e79a0d8f93fac18b"`);
        await queryRunner.query(`ALTER TABLE "ads" DROP CONSTRAINT "FK_976329689f839dacbbf7f5064f1"`);
        await queryRunner.query(`ALTER TABLE "seller_applications" DROP CONSTRAINT "FK_7c42b24cc2b0d31522da8980ae1"`);
        await queryRunner.query(`ALTER TABLE "seller_applications" DROP CONSTRAINT "FK_bc16b54496faa4ffae868a999ce"`);
        await queryRunner.query(`ALTER TABLE "quote_requests" DROP CONSTRAINT "FK_311cb32eb9f6a5fd66e107e9859"`);
        await queryRunner.query(`ALTER TABLE "quote_requests" DROP CONSTRAINT "FK_e1a045c634da80087abaa5ff7d9"`);
        await queryRunner.query(`ALTER TABLE "order_disputes" DROP CONSTRAINT "FK_75b03066015a2e90207e11a66bb"`);
        await queryRunner.query(`ALTER TABLE "company_reviews" DROP CONSTRAINT "FK_fc32a8670ebb0ad696469b97afb"`);
        await queryRunner.query(`ALTER TABLE "saved_jobs" DROP CONSTRAINT "FK_bb1b729967b423ec7f29f11b9c5"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "FK_2db9cf2b3ca111742793f6c37ce"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "FK_acf951a58e3b9611dd96ce89042"`);
        await queryRunner.query(`ALTER TABLE "reported_jobs" DROP CONSTRAINT "FK_e2ec41e00fdd27123387b39bc1a"`);
        await queryRunner.query(`ALTER TABLE "jobs" DROP CONSTRAINT "FK_62e3afafda3cf7db0a08982a5b1"`);
        await queryRunner.query(`ALTER TABLE "shop_products" DROP CONSTRAINT "FK_2152bfc72d8d56f3aa9fb790cf0"`);
        await queryRunner.query(`ALTER TABLE "applications" DROP CONSTRAINT "FK_cb2d6c1b818d394eedb4520569f"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_1c382880db667beb75d26c57873"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_9877ffd9a491c3e82f5b32d4f4d"`);
        await queryRunner.query(`ALTER TABLE "seeker_profiles" DROP CONSTRAINT "FK_6e42387b0ad6b11de38844b67b4"`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "contact_phone"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "contact_phone" character varying`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "whatsapp_phone"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "whatsapp_phone" character varying`);
        await queryRunner.query(`ALTER TABLE "seeker_profiles" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "seeker_profiles" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "seeker_profiles" DROP COLUMN "contact_phone"`);
        await queryRunner.query(`ALTER TABLE "seeker_profiles" ADD "contact_phone" character varying`);
        await queryRunner.query(`ALTER TABLE "seeker_profiles" DROP COLUMN "contact_whatsapp"`);
        await queryRunner.query(`ALTER TABLE "seeker_profiles" ADD "contact_whatsapp" character varying`);
        await queryRunner.query(`ALTER TABLE "legal_pages" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "legal_pages" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "ads" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "ads" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "seller_applications" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "seller_applications" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "shop_subcategories" DROP CONSTRAINT "FK_1d80d0a4050fe1e4b8d806afaf7"`);
        await queryRunner.query(`ALTER TABLE "shop_categories" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "shop_categories" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "shop_products" DROP CONSTRAINT "FK_5984ad2e18aaab20b68e5f3f290"`);
        await queryRunner.query(`ALTER TABLE "shop_subcategories" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "shop_subcategories" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "quote_requests" DROP CONSTRAINT "FK_7523ac689356c6f0a38265a9a66"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_8624dad595ae567818ad9983b33"`);
        await queryRunner.query(`ALTER TABLE "shop_products" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "shop_products" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "shop_products" ALTER COLUMN "rating_distribution" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "order_disputes" DROP CONSTRAINT "FK_3f57473d7c86a1aeb531ac49bae"`);
        await queryRunner.query(`ALTER TABLE "payment_transaction_audit" DROP CONSTRAINT "FK_3a25a0d453b0956c52d45fc871f"`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "quote_requests" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "quote_requests" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "order_disputes" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "order_disputes" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`COMMENT ON COLUMN "payment_transaction_audit"."gateway" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "payment_transaction_audit"."reference" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "payment_transaction_audit"."status" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "payment_transaction_audit"."gatewayResponse" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "payment_transaction_audit"."errorMessage" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "payment_transaction_audit"."idempotencyKey" IS NULL`);
        await queryRunner.query(`ALTER TABLE "payment_transaction_audit" ALTER COLUMN "orderId" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "product_ratings" ALTER COLUMN "rating" SET DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE "company_reviews" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "company_reviews" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "salary_reviews" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "salary_reviews" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "saved_jobs" DROP CONSTRAINT "FK_d881f4ad49b0839b3f14b67e6d7"`);
        await queryRunner.query(`ALTER TABLE "reported_jobs" DROP CONSTRAINT "FK_b2b740ab97f78fa13ccaf4fb516"`);
        await queryRunner.query(`ALTER TABLE "applications" DROP CONSTRAINT "FK_f6ebb8bc5061068e4dd97df3c77"`);
        await queryRunner.query(`ALTER TABLE "jobs" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "jobs" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "applications" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "applications" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "saved_jobs" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "saved_jobs" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "reported_jobs" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "reported_jobs" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "post_comments" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "post_comments" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "post_comments" ALTER COLUMN "updatedAt" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "post_comments" ALTER COLUMN "updatedAt" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "post_likes" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "post_likes" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "reports" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "reports" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "reports" DROP COLUMN "reason"`);
        await queryRunner.query(`CREATE TYPE "public"."reports_reason_enum" AS ENUM('inappropriate', 'spam', 'harassment', 'misinformation', 'copyright', 'other')`);
        await queryRunner.query(`ALTER TABLE "reports" ADD "reason" "public"."reports_reason_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "posts" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "posts" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "follows" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "follows" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TYPE "public"."follows_status_enum" RENAME TO "follows_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."follows_status_enum" AS ENUM('pending', 'accepted')`);
        await queryRunner.query(`ALTER TABLE "follows" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "follows" ALTER COLUMN "status" TYPE "public"."follows_status_enum" USING "status"::"text"::"public"."follows_status_enum"`);
        await queryRunner.query(`ALTER TABLE "follows" ALTER COLUMN "status" SET DEFAULT 'accepted'`);
        await queryRunner.query(`DROP TYPE "public"."follows_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "posts" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "posts" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "post_likes" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "post_likes" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "post_comments" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "post_comments" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "follows" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "follows" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "messages" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "messages" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "post_saves" ALTER COLUMN "createdAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "post_saves" ALTER COLUMN "updatedAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "post_saves" ALTER COLUMN "userId" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "post_saves" ALTER COLUMN "postId" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "post_shares" ALTER COLUMN "createdAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "post_shares" ALTER COLUMN "updatedAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "post_shares" ALTER COLUMN "originalPostId" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "post_shares" ALTER COLUMN "sharedById" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "reports" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "reports" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "reports" DROP COLUMN "reason"`);
        await queryRunner.query(`ALTER TABLE "reports" ADD "reason" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP COLUMN "type"`);
        await queryRunner.query(`CREATE TYPE "public"."notifications_type_enum" AS ENUM('follow_request', 'follow_accepted', 'post_liked', 'post_commented', 'job_application_status', 'job_approved', 'order_completed', 'order_disputed', 'review_approved', 'seller_application_decision', 'message_received', 'platform_announcement', 'ad_campaign_created', 'ad_under_review', 'ad_approved', 'ad_rejected', 'ad_budget_50', 'ad_budget_80', 'ad_budget_exhausted', 'ad_campaign_ended', 'ad_refund_processed', 'ad_weekly_report')`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD "type" "public"."notifications_type_enum" NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_692a909ee0fa9383e7859f9b40" ON "notifications" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_993f8cb0705c30d5831eb8a997" ON "product_ratings" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_7fb4174621654595a90dc1fcbf" ON "product_ratings" ("buyerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_1755b3b00e1d9f8cad4632324d" ON "product_ratings" ("productId") `);
        await queryRunner.query(`CREATE INDEX "IDX_f507ad1fe17ee792435ef5d1fb" ON "post_comments" ("postId", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_6999d13aca25e33515210abaf1" ON "post_likes" ("postId") `);
        await queryRunner.query(`CREATE INDEX "IDX_781a2c0adee4125f1f6906a14a" ON "reports" ("status", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_d41ac738d6a1f85a3cd96b6f45" ON "reports" ("postId", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_46bc204f43827b6f25e0133dbf" ON "posts" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_65d5fbf616c25e628a12898e68" ON "posts" ("authorId", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_ffe1a0dd18b12c71c182381d27" ON "follows" ("followingId", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_7d32d01e270a821b03fa7089b3" ON "follows" ("followerId", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_5340fc241f57310d243e5ab20b" ON "notifications" ("userId", "isRead") `);
        await queryRunner.query(`CREATE INDEX "IDX_21e65af2f4f242d4c85a92aff4" ON "notifications" ("userId", "createdAt") `);
        await queryRunner.query(`ALTER TABLE "product_ratings" ADD CONSTRAINT "UQ_d5c8af8c4ed11fad6f63c50f7a6" UNIQUE ("productId", "buyerId")`);
        await queryRunner.query(`ALTER TABLE "follows" ADD CONSTRAINT "UQ_105079775692df1f8799ed0fac8" UNIQUE ("followerId", "followingId")`);
        await queryRunner.query(`ALTER TABLE "follows" ADD CONSTRAINT "UQ_63cae1eb7767feee4555f00c5f1" UNIQUE ("followerId", "followeeId")`);
        await queryRunner.query(`ALTER TABLE "post_saves" ADD CONSTRAINT "UQ_578cb9c4f13bcb6ac2710de4105" UNIQUE ("userId", "postId")`);
        await queryRunner.query(`ALTER TABLE "employer_profiles" ADD CONSTRAINT "FK_9800cae27bdc0b9cbbc16e1556a" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "seeker_profiles" ADD CONSTRAINT "FK_6e42387b0ad6b11de38844b67b4" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_settings" ADD CONSTRAINT "FK_986a2b6d3c05eb4091bb8066f78" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "legal_pages" ADD CONSTRAINT "FK_5addf284971e79a0d8f93fac18b" FOREIGN KEY ("updatedById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ads" ADD CONSTRAINT "FK_976329689f839dacbbf7f5064f1" FOREIGN KEY ("advertiserId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_692a909ee0fa9383e7859f9b406" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "seller_applications" ADD CONSTRAINT "FK_bc16b54496faa4ffae868a999ce" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "seller_applications" ADD CONSTRAINT "FK_7c42b24cc2b0d31522da8980ae1" FOREIGN KEY ("reviewedById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shop_subcategories" ADD CONSTRAINT "FK_1d80d0a4050fe1e4b8d806afaf7" FOREIGN KEY ("categoryId") REFERENCES "shop_categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shop_products" ADD CONSTRAINT "FK_2152bfc72d8d56f3aa9fb790cf0" FOREIGN KEY ("sellerId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shop_products" ADD CONSTRAINT "FK_5984ad2e18aaab20b68e5f3f290" FOREIGN KEY ("subcategoryId") REFERENCES "shop_subcategories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_9877ffd9a491c3e82f5b32d4f4d" FOREIGN KEY ("buyerId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_8624dad595ae567818ad9983b33" FOREIGN KEY ("productId") REFERENCES "shop_products"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_1c382880db667beb75d26c57873" FOREIGN KEY ("sellerId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "quote_requests" ADD CONSTRAINT "FK_7523ac689356c6f0a38265a9a66" FOREIGN KEY ("productId") REFERENCES "shop_products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "quote_requests" ADD CONSTRAINT "FK_311cb32eb9f6a5fd66e107e9859" FOREIGN KEY ("buyerId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "quote_requests" ADD CONSTRAINT "FK_e1a045c634da80087abaa5ff7d9" FOREIGN KEY ("sellerId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_disputes" ADD CONSTRAINT "FK_3f57473d7c86a1aeb531ac49bae" FOREIGN KEY ("orderId") REFERENCES "orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_disputes" ADD CONSTRAINT "FK_75b03066015a2e90207e11a66bb" FOREIGN KEY ("raisedById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_disputes" ADD CONSTRAINT "FK_dbfcae8c201fe56e5404e680096" FOREIGN KEY ("resolved_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment_transaction_audit" ADD CONSTRAINT "FK_3a25a0d453b0956c52d45fc871f" FOREIGN KEY ("orderId") REFERENCES "orders"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_ratings" ADD CONSTRAINT "FK_1755b3b00e1d9f8cad4632324db" FOREIGN KEY ("productId") REFERENCES "shop_products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_ratings" ADD CONSTRAINT "FK_7fb4174621654595a90dc1fcbf3" FOREIGN KEY ("buyerId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "company_reviews" ADD CONSTRAINT "FK_fc32a8670ebb0ad696469b97afb" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "jobs" ADD CONSTRAINT "FK_62e3afafda3cf7db0a08982a5b1" FOREIGN KEY ("employerId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "applications" ADD CONSTRAINT "FK_f6ebb8bc5061068e4dd97df3c77" FOREIGN KEY ("jobId") REFERENCES "jobs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "applications" ADD CONSTRAINT "FK_cb2d6c1b818d394eedb4520569f" FOREIGN KEY ("seekerId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "saved_jobs" ADD CONSTRAINT "FK_d881f4ad49b0839b3f14b67e6d7" FOREIGN KEY ("jobId") REFERENCES "jobs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "saved_jobs" ADD CONSTRAINT "FK_bb1b729967b423ec7f29f11b9c5" FOREIGN KEY ("seekerId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reported_jobs" ADD CONSTRAINT "FK_b2b740ab97f78fa13ccaf4fb516" FOREIGN KEY ("jobId") REFERENCES "jobs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reported_jobs" ADD CONSTRAINT "FK_e2ec41e00fdd27123387b39bc1a" FOREIGN KEY ("reporterId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "post_comments" ADD CONSTRAINT "FK_ac65d744abc05279aee0b290857" FOREIGN KEY ("postId") REFERENCES "posts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "post_comments" ADD CONSTRAINT "FK_2b93091c2f4d6c9cf7c9b32e29f" FOREIGN KEY ("authorId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "post_likes" ADD CONSTRAINT "FK_6999d13aca25e33515210abaf16" FOREIGN KEY ("postId") REFERENCES "posts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "post_likes" ADD CONSTRAINT "FK_37d337ad54b1aa6b9a44415a498" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reports" ADD CONSTRAINT "FK_6bebfa3fc68a35f5af3f9883c4e" FOREIGN KEY ("postId") REFERENCES "posts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reports" ADD CONSTRAINT "FK_4353be8309ce86650def2f8572d" FOREIGN KEY ("reporterId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "posts" ADD CONSTRAINT "FK_c5a322ad12a7bf95460c958e80e" FOREIGN KEY ("authorId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "saved_posts" ADD CONSTRAINT "FK_2a6ac38aa1767f692d4f492639b" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "saved_posts" ADD CONSTRAINT "FK_4704fa96cd2b591592a8cfaee56" FOREIGN KEY ("postId") REFERENCES "posts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "follows" ADD CONSTRAINT "FK_fdb91868b03a2040db408a53331" FOREIGN KEY ("followerId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "follows" ADD CONSTRAINT "FK_ef463dd9a2ce0d673350e36e0fb" FOREIGN KEY ("followingId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "follows" ADD CONSTRAINT "FK_666a44940ce8279976767c6b5e3" FOREIGN KEY ("followeeId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "FK_2db9cf2b3ca111742793f6c37ce" FOREIGN KEY ("senderId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "FK_acf951a58e3b9611dd96ce89042" FOREIGN KEY ("receiverId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "post_saves" ADD CONSTRAINT "FK_15b357815f5e6a765e60ee0e32e" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "post_saves" ADD CONSTRAINT "FK_08107d1d38fc71d50702e1a8733" FOREIGN KEY ("postId") REFERENCES "posts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "post_shares" ADD CONSTRAINT "FK_15ea4c725c1f17facbc53b75e53" FOREIGN KEY ("originalPostId") REFERENCES "posts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "post_shares" ADD CONSTRAINT "FK_95c8a0c593c2320addcc7af1468" FOREIGN KEY ("sharedById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "newsletter_sends" ADD CONSTRAINT "FK_8a8178231661de0cf113f92a605" FOREIGN KEY ("sentById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "announcements" ADD CONSTRAINT "FK_197a06ce0989e489974fdc26ca8" FOREIGN KEY ("createdById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "announcements" DROP CONSTRAINT "FK_197a06ce0989e489974fdc26ca8"`);
        await queryRunner.query(`ALTER TABLE "newsletter_sends" DROP CONSTRAINT "FK_8a8178231661de0cf113f92a605"`);
        await queryRunner.query(`ALTER TABLE "post_shares" DROP CONSTRAINT "FK_95c8a0c593c2320addcc7af1468"`);
        await queryRunner.query(`ALTER TABLE "post_shares" DROP CONSTRAINT "FK_15ea4c725c1f17facbc53b75e53"`);
        await queryRunner.query(`ALTER TABLE "post_saves" DROP CONSTRAINT "FK_08107d1d38fc71d50702e1a8733"`);
        await queryRunner.query(`ALTER TABLE "post_saves" DROP CONSTRAINT "FK_15b357815f5e6a765e60ee0e32e"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "FK_acf951a58e3b9611dd96ce89042"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "FK_2db9cf2b3ca111742793f6c37ce"`);
        await queryRunner.query(`ALTER TABLE "follows" DROP CONSTRAINT "FK_666a44940ce8279976767c6b5e3"`);
        await queryRunner.query(`ALTER TABLE "follows" DROP CONSTRAINT "FK_ef463dd9a2ce0d673350e36e0fb"`);
        await queryRunner.query(`ALTER TABLE "follows" DROP CONSTRAINT "FK_fdb91868b03a2040db408a53331"`);
        await queryRunner.query(`ALTER TABLE "saved_posts" DROP CONSTRAINT "FK_4704fa96cd2b591592a8cfaee56"`);
        await queryRunner.query(`ALTER TABLE "saved_posts" DROP CONSTRAINT "FK_2a6ac38aa1767f692d4f492639b"`);
        await queryRunner.query(`ALTER TABLE "posts" DROP CONSTRAINT "FK_c5a322ad12a7bf95460c958e80e"`);
        await queryRunner.query(`ALTER TABLE "reports" DROP CONSTRAINT "FK_4353be8309ce86650def2f8572d"`);
        await queryRunner.query(`ALTER TABLE "reports" DROP CONSTRAINT "FK_6bebfa3fc68a35f5af3f9883c4e"`);
        await queryRunner.query(`ALTER TABLE "post_likes" DROP CONSTRAINT "FK_37d337ad54b1aa6b9a44415a498"`);
        await queryRunner.query(`ALTER TABLE "post_likes" DROP CONSTRAINT "FK_6999d13aca25e33515210abaf16"`);
        await queryRunner.query(`ALTER TABLE "post_comments" DROP CONSTRAINT "FK_2b93091c2f4d6c9cf7c9b32e29f"`);
        await queryRunner.query(`ALTER TABLE "post_comments" DROP CONSTRAINT "FK_ac65d744abc05279aee0b290857"`);
        await queryRunner.query(`ALTER TABLE "reported_jobs" DROP CONSTRAINT "FK_e2ec41e00fdd27123387b39bc1a"`);
        await queryRunner.query(`ALTER TABLE "reported_jobs" DROP CONSTRAINT "FK_b2b740ab97f78fa13ccaf4fb516"`);
        await queryRunner.query(`ALTER TABLE "saved_jobs" DROP CONSTRAINT "FK_bb1b729967b423ec7f29f11b9c5"`);
        await queryRunner.query(`ALTER TABLE "saved_jobs" DROP CONSTRAINT "FK_d881f4ad49b0839b3f14b67e6d7"`);
        await queryRunner.query(`ALTER TABLE "applications" DROP CONSTRAINT "FK_cb2d6c1b818d394eedb4520569f"`);
        await queryRunner.query(`ALTER TABLE "applications" DROP CONSTRAINT "FK_f6ebb8bc5061068e4dd97df3c77"`);
        await queryRunner.query(`ALTER TABLE "jobs" DROP CONSTRAINT "FK_62e3afafda3cf7db0a08982a5b1"`);
        await queryRunner.query(`ALTER TABLE "company_reviews" DROP CONSTRAINT "FK_fc32a8670ebb0ad696469b97afb"`);
        await queryRunner.query(`ALTER TABLE "product_ratings" DROP CONSTRAINT "FK_7fb4174621654595a90dc1fcbf3"`);
        await queryRunner.query(`ALTER TABLE "product_ratings" DROP CONSTRAINT "FK_1755b3b00e1d9f8cad4632324db"`);
        await queryRunner.query(`ALTER TABLE "payment_transaction_audit" DROP CONSTRAINT "FK_3a25a0d453b0956c52d45fc871f"`);
        await queryRunner.query(`ALTER TABLE "order_disputes" DROP CONSTRAINT "FK_dbfcae8c201fe56e5404e680096"`);
        await queryRunner.query(`ALTER TABLE "order_disputes" DROP CONSTRAINT "FK_75b03066015a2e90207e11a66bb"`);
        await queryRunner.query(`ALTER TABLE "order_disputes" DROP CONSTRAINT "FK_3f57473d7c86a1aeb531ac49bae"`);
        await queryRunner.query(`ALTER TABLE "quote_requests" DROP CONSTRAINT "FK_e1a045c634da80087abaa5ff7d9"`);
        await queryRunner.query(`ALTER TABLE "quote_requests" DROP CONSTRAINT "FK_311cb32eb9f6a5fd66e107e9859"`);
        await queryRunner.query(`ALTER TABLE "quote_requests" DROP CONSTRAINT "FK_7523ac689356c6f0a38265a9a66"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_1c382880db667beb75d26c57873"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_8624dad595ae567818ad9983b33"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_9877ffd9a491c3e82f5b32d4f4d"`);
        await queryRunner.query(`ALTER TABLE "shop_products" DROP CONSTRAINT "FK_5984ad2e18aaab20b68e5f3f290"`);
        await queryRunner.query(`ALTER TABLE "shop_products" DROP CONSTRAINT "FK_2152bfc72d8d56f3aa9fb790cf0"`);
        await queryRunner.query(`ALTER TABLE "shop_subcategories" DROP CONSTRAINT "FK_1d80d0a4050fe1e4b8d806afaf7"`);
        await queryRunner.query(`ALTER TABLE "seller_applications" DROP CONSTRAINT "FK_7c42b24cc2b0d31522da8980ae1"`);
        await queryRunner.query(`ALTER TABLE "seller_applications" DROP CONSTRAINT "FK_bc16b54496faa4ffae868a999ce"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_692a909ee0fa9383e7859f9b406"`);
        await queryRunner.query(`ALTER TABLE "ads" DROP CONSTRAINT "FK_976329689f839dacbbf7f5064f1"`);
        await queryRunner.query(`ALTER TABLE "legal_pages" DROP CONSTRAINT "FK_5addf284971e79a0d8f93fac18b"`);
        await queryRunner.query(`ALTER TABLE "user_settings" DROP CONSTRAINT "FK_986a2b6d3c05eb4091bb8066f78"`);
        await queryRunner.query(`ALTER TABLE "seeker_profiles" DROP CONSTRAINT "FK_6e42387b0ad6b11de38844b67b4"`);
        await queryRunner.query(`ALTER TABLE "employer_profiles" DROP CONSTRAINT "FK_9800cae27bdc0b9cbbc16e1556a"`);
        await queryRunner.query(`ALTER TABLE "post_saves" DROP CONSTRAINT "UQ_578cb9c4f13bcb6ac2710de4105"`);
        await queryRunner.query(`ALTER TABLE "follows" DROP CONSTRAINT "UQ_63cae1eb7767feee4555f00c5f1"`);
        await queryRunner.query(`ALTER TABLE "follows" DROP CONSTRAINT "UQ_105079775692df1f8799ed0fac8"`);
        await queryRunner.query(`ALTER TABLE "product_ratings" DROP CONSTRAINT "UQ_d5c8af8c4ed11fad6f63c50f7a6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_21e65af2f4f242d4c85a92aff4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5340fc241f57310d243e5ab20b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7d32d01e270a821b03fa7089b3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ffe1a0dd18b12c71c182381d27"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_65d5fbf616c25e628a12898e68"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_46bc204f43827b6f25e0133dbf"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d41ac738d6a1f85a3cd96b6f45"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_781a2c0adee4125f1f6906a14a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6999d13aca25e33515210abaf1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f507ad1fe17ee792435ef5d1fb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1755b3b00e1d9f8cad4632324d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7fb4174621654595a90dc1fcbf"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_993f8cb0705c30d5831eb8a997"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_692a909ee0fa9383e7859f9b40"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP COLUMN "type"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_type_enum"`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD "type" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "id" SET DEFAULT extensions.uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "reports" DROP COLUMN "reason"`);
        await queryRunner.query(`ALTER TABLE "reports" ADD "reason" "public"."reports_reason_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "reports" ALTER COLUMN "id" SET DEFAULT extensions.uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "reports" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "post_shares" ALTER COLUMN "sharedById" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "post_shares" ALTER COLUMN "originalPostId" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "post_shares" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "post_shares" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "post_saves" ALTER COLUMN "postId" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "post_saves" ALTER COLUMN "userId" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "post_saves" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "post_saves" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "messages" ALTER COLUMN "id" SET DEFAULT extensions.uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "messages" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "follows" ALTER COLUMN "id" SET DEFAULT extensions.uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "follows" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "post_comments" ALTER COLUMN "id" SET DEFAULT extensions.uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "post_comments" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "post_likes" ALTER COLUMN "id" SET DEFAULT extensions.uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "post_likes" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "posts" ALTER COLUMN "id" SET DEFAULT extensions.uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "posts" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`CREATE TYPE "public"."follows_status_enum_old" AS ENUM('pending', 'accepted', 'rejected')`);
        await queryRunner.query(`ALTER TABLE "follows" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "follows" ALTER COLUMN "status" TYPE "public"."follows_status_enum_old" USING "status"::"text"::"public"."follows_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "follows" ALTER COLUMN "status" SET DEFAULT 'pending'`);
        await queryRunner.query(`DROP TYPE "public"."follows_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."follows_status_enum_old" RENAME TO "follows_status_enum"`);
        await queryRunner.query(`ALTER TABLE "follows" ALTER COLUMN "id" SET DEFAULT extensions.uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "follows" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "posts" ALTER COLUMN "id" SET DEFAULT extensions.uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "posts" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "reports" DROP COLUMN "reason"`);
        await queryRunner.query(`DROP TYPE "public"."reports_reason_enum"`);
        await queryRunner.query(`ALTER TABLE "reports" ADD "reason" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "reports" ALTER COLUMN "id" SET DEFAULT extensions.uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "reports" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "post_likes" ALTER COLUMN "id" SET DEFAULT extensions.uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "post_likes" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "post_comments" ALTER COLUMN "updatedAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "post_comments" ALTER COLUMN "updatedAt" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "post_comments" ALTER COLUMN "id" SET DEFAULT extensions.uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "post_comments" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "reported_jobs" ALTER COLUMN "id" SET DEFAULT extensions.uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "reported_jobs" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "saved_jobs" ALTER COLUMN "id" SET DEFAULT extensions.uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "saved_jobs" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "applications" ALTER COLUMN "id" SET DEFAULT extensions.uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "applications" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "jobs" ALTER COLUMN "id" SET DEFAULT extensions.uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "jobs" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "applications" ADD CONSTRAINT "FK_f6ebb8bc5061068e4dd97df3c77" FOREIGN KEY ("jobId") REFERENCES "jobs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reported_jobs" ADD CONSTRAINT "FK_b2b740ab97f78fa13ccaf4fb516" FOREIGN KEY ("jobId") REFERENCES "jobs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "saved_jobs" ADD CONSTRAINT "FK_d881f4ad49b0839b3f14b67e6d7" FOREIGN KEY ("jobId") REFERENCES "jobs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "salary_reviews" ALTER COLUMN "id" SET DEFAULT extensions.uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "salary_reviews" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "company_reviews" ALTER COLUMN "id" SET DEFAULT extensions.uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "company_reviews" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "product_ratings" ALTER COLUMN "rating" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "payment_transaction_audit" ALTER COLUMN "orderId" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "payment_transaction_audit"."idempotencyKey" IS 'For preventing duplicate processing'`);
        await queryRunner.query(`COMMENT ON COLUMN "payment_transaction_audit"."errorMessage" IS 'Error details if transaction failed'`);
        await queryRunner.query(`COMMENT ON COLUMN "payment_transaction_audit"."gatewayResponse" IS 'Full response from payment gateway for debugging'`);
        await queryRunner.query(`COMMENT ON COLUMN "payment_transaction_audit"."status" IS 'initiated, pending, successful, failed, refunded, etc.'`);
        await queryRunner.query(`COMMENT ON COLUMN "payment_transaction_audit"."reference" IS 'Payment reference from gateway'`);
        await queryRunner.query(`COMMENT ON COLUMN "payment_transaction_audit"."gateway" IS 'flutterwave, paystack, etc.'`);
        await queryRunner.query(`ALTER TABLE "order_disputes" ALTER COLUMN "id" SET DEFAULT extensions.uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "order_disputes" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "quote_requests" ALTER COLUMN "id" SET DEFAULT extensions.uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "quote_requests" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "id" SET DEFAULT extensions.uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "payment_transaction_audit" ADD CONSTRAINT "FK_3a25a0d453b0956c52d45fc871f" FOREIGN KEY ("orderId") REFERENCES "orders"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_disputes" ADD CONSTRAINT "FK_3f57473d7c86a1aeb531ac49bae" FOREIGN KEY ("orderId") REFERENCES "orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shop_products" ALTER COLUMN "rating_distribution" SET DEFAULT '{}'`);
        await queryRunner.query(`ALTER TABLE "shop_products" ALTER COLUMN "id" SET DEFAULT extensions.uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "shop_products" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_8624dad595ae567818ad9983b33" FOREIGN KEY ("productId") REFERENCES "shop_products"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "quote_requests" ADD CONSTRAINT "FK_7523ac689356c6f0a38265a9a66" FOREIGN KEY ("productId") REFERENCES "shop_products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shop_subcategories" ALTER COLUMN "id" SET DEFAULT extensions.uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "shop_subcategories" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "shop_products" ADD CONSTRAINT "FK_5984ad2e18aaab20b68e5f3f290" FOREIGN KEY ("subcategoryId") REFERENCES "shop_subcategories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shop_categories" ALTER COLUMN "id" SET DEFAULT extensions.uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "shop_categories" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "shop_subcategories" ADD CONSTRAINT "FK_1d80d0a4050fe1e4b8d806afaf7" FOREIGN KEY ("categoryId") REFERENCES "shop_categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "seller_applications" ALTER COLUMN "id" SET DEFAULT extensions.uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "seller_applications" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "id" SET DEFAULT extensions.uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "ads" ALTER COLUMN "id" SET DEFAULT extensions.uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "ads" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "legal_pages" ALTER COLUMN "id" SET DEFAULT extensions.uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "legal_pages" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "seeker_profiles" DROP COLUMN "contact_whatsapp"`);
        await queryRunner.query(`ALTER TABLE "seeker_profiles" ADD "contact_whatsapp" character varying(20)`);
        await queryRunner.query(`ALTER TABLE "seeker_profiles" DROP COLUMN "contact_phone"`);
        await queryRunner.query(`ALTER TABLE "seeker_profiles" ADD "contact_phone" character varying(20)`);
        await queryRunner.query(`ALTER TABLE "seeker_profiles" ALTER COLUMN "id" SET DEFAULT extensions.uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "seeker_profiles" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "whatsapp_phone"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "whatsapp_phone" character varying(20)`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "contact_phone"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "contact_phone" character varying(20)`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "id" SET DEFAULT extensions.uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "seeker_profiles" ADD CONSTRAINT "FK_6e42387b0ad6b11de38844b67b4" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_9877ffd9a491c3e82f5b32d4f4d" FOREIGN KEY ("buyerId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_1c382880db667beb75d26c57873" FOREIGN KEY ("sellerId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "applications" ADD CONSTRAINT "FK_cb2d6c1b818d394eedb4520569f" FOREIGN KEY ("seekerId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shop_products" ADD CONSTRAINT "FK_2152bfc72d8d56f3aa9fb790cf0" FOREIGN KEY ("sellerId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "jobs" ADD CONSTRAINT "FK_62e3afafda3cf7db0a08982a5b1" FOREIGN KEY ("employerId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reported_jobs" ADD CONSTRAINT "FK_e2ec41e00fdd27123387b39bc1a" FOREIGN KEY ("reporterId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "FK_acf951a58e3b9611dd96ce89042" FOREIGN KEY ("receiverId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "FK_2db9cf2b3ca111742793f6c37ce" FOREIGN KEY ("senderId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "saved_jobs" ADD CONSTRAINT "FK_bb1b729967b423ec7f29f11b9c5" FOREIGN KEY ("seekerId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "company_reviews" ADD CONSTRAINT "FK_fc32a8670ebb0ad696469b97afb" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_disputes" ADD CONSTRAINT "FK_75b03066015a2e90207e11a66bb" FOREIGN KEY ("raisedById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "quote_requests" ADD CONSTRAINT "FK_e1a045c634da80087abaa5ff7d9" FOREIGN KEY ("sellerId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "quote_requests" ADD CONSTRAINT "FK_311cb32eb9f6a5fd66e107e9859" FOREIGN KEY ("buyerId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "seller_applications" ADD CONSTRAINT "FK_bc16b54496faa4ffae868a999ce" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "seller_applications" ADD CONSTRAINT "FK_7c42b24cc2b0d31522da8980ae1" FOREIGN KEY ("reviewedById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ads" ADD CONSTRAINT "FK_976329689f839dacbbf7f5064f1" FOREIGN KEY ("advertiserId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "legal_pages" ADD CONSTRAINT "FK_5addf284971e79a0d8f93fac18b" FOREIGN KEY ("updatedById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employer_profiles" ADD CONSTRAINT "FK_9800cae27bdc0b9cbbc16e1556a" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employer_profiles" ALTER COLUMN "id" SET DEFAULT extensions.uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "employer_profiles" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "reports" DROP COLUMN "targetId"`);
        await queryRunner.query(`ALTER TABLE "reports" DROP COLUMN "targetType"`);
        await queryRunner.query(`ALTER TABLE "reports" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "follows" DROP COLUMN "followeeId"`);
        await queryRunner.query(`ALTER TABLE "follows" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "post_comments" DROP COLUMN "body"`);
        await queryRunner.query(`ALTER TABLE "post_likes" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "follows" DROP COLUMN "followingId"`);
        await queryRunner.query(`ALTER TABLE "follows" DROP COLUMN "acceptedAt"`);
        await queryRunner.query(`ALTER TABLE "reports" DROP COLUMN "postId"`);
        await queryRunner.query(`ALTER TABLE "reports" DROP COLUMN "reviewedBy"`);
        await queryRunner.query(`ALTER TABLE "reports" DROP COLUMN "reviewedAt"`);
        await queryRunner.query(`ALTER TABLE "reports" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."reports_status_enum"`);
        await queryRunner.query(`ALTER TABLE "reports" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "post_comments" DROP COLUMN "content"`);
        await queryRunner.query(`ALTER TABLE "product_ratings" DROP COLUMN "buyerId"`);
        await queryRunner.query(`ALTER TABLE "product_ratings" DROP COLUMN "productId"`);
        await queryRunner.query(`ALTER TABLE "product_ratings" DROP COLUMN "orderId"`);
        await queryRunner.query(`ALTER TABLE "product_ratings" DROP COLUMN "isVerifiedPurchase"`);
        await queryRunner.query(`ALTER TABLE "product_ratings" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "product_ratings" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "follows" ADD "followeeId" uuid`);
        await queryRunner.query(`ALTER TABLE "follows" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "posts" ADD "imageUrl" character varying`);
        await queryRunner.query(`ALTER TABLE "reports" ADD "targetId" uuid NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."reports_targettype_enum" AS ENUM('post', 'review', 'job', 'user')`);
        await queryRunner.query(`ALTER TABLE "reports" ADD "targetType" "public"."reports_targettype_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "reports" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "post_likes" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "post_comments" ADD "body" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "product_ratings" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "product_ratings" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "product_ratings" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "product_ratings" ADD "order_id" uuid`);
        await queryRunner.query(`ALTER TABLE "product_ratings" ADD "is_verified_purchase" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "product_ratings" ADD "buyer_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "product_ratings" ADD "product_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "order_disputes" ADD "resolvedById" uuid`);
        await queryRunner.query(`ALTER TABLE "order_disputes" ADD "resolvedAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "order_disputes" ADD "resolutionNotes" text`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "autoconfirmscheduledat" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "confirmedat" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "shop_products" ADD "ratingdistribution" jsonb DEFAULT '{}'`);
        await queryRunner.query(`ALTER TABLE "shop_products" ADD "totalratings" integer DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "shop_products" ADD "averagerating" numeric(3,2) DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "users" ADD "isdeleted" boolean DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "users" ADD "issuspended" boolean DEFAULT false`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b2b1d571903f71883bc942f2ed"`);
        await queryRunner.query(`DROP TABLE "saved_posts"`);
        await queryRunner.query(`ALTER TABLE "follows" ADD CONSTRAINT "UQ_63cae1eb7767feee4555f00c5f1" UNIQUE ("followerId", "followeeId")`);
        await queryRunner.query(`CREATE INDEX "IDX_692a909ee0fa9383e7859f9b40" ON "notifications" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_82c4b7dc16c5f5995ce6cf8592" ON "post_shares" ("createdAt", "sharedById") `);
        await queryRunner.query(`CREATE INDEX "IDX_15ea4c725c1f17facbc53b75e5" ON "post_shares" ("originalPostId") `);
        await queryRunner.query(`CREATE INDEX "IDX_bc696393201e2083ea0db9d58d" ON "post_saves" ("createdAt", "userId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_578cb9c4f13bcb6ac2710de410" ON "post_saves" ("postId", "userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_65d5fbf616c25e628a12898e68" ON "posts" ("authorId", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_fccf8ad12448a532feb8127280" ON "posts" ("createdAt", "id") `);
        await queryRunner.query(`CREATE INDEX "IDX_19d30f9d2260c7a9f1f55fa346" ON "product_ratings" ("created_at") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_407d527627ceff1a5590eaba06" ON "product_ratings" ("buyer_id", "product_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_7f190f97558c87ec1c14a3d637" ON "product_ratings" ("buyer_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_538c9489e98d4874e8db0c4caf" ON "product_ratings" ("product_id") `);
        await queryRunner.query(`CREATE INDEX "idx_payment_audit_created" ON "payment_transaction_audit" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "idx_payment_audit_status" ON "payment_transaction_audit" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_payment_audit_gateway" ON "payment_transaction_audit" ("gateway") `);
        await queryRunner.query(`CREATE INDEX "idx_payment_audit_reference" ON "payment_transaction_audit" ("reference") `);
        await queryRunner.query(`CREATE INDEX "idx_payment_audit_order" ON "payment_transaction_audit" ("orderId") `);
        await queryRunner.query(`CREATE INDEX "idx_shop_products_featured_search_vector" ON "shop_products" ("featured_search_vector") `);
        await queryRunner.query(`CREATE INDEX "idx_shop_products_featured_until" ON "shop_products" ("featured_until") WHERE (featured_until IS NOT NULL)`);
        await queryRunner.query(`CREATE INDEX "idx_shop_products_average_rating" ON "shop_products" ("average_rating") `);
        await queryRunner.query(`CREATE INDEX "idx_seeker_profiles_seller_plan" ON "seeker_profiles" ("seller_plan") `);
        await queryRunner.query(`ALTER TABLE "announcements" ADD CONSTRAINT "FK_announcements_createdBy" FOREIGN KEY ("createdById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "newsletter_sends" ADD CONSTRAINT "FK_newsletter_sends_sentBy" FOREIGN KEY ("sentById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_692a909ee0fa9383e7859f9b406" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "post_shares" ADD CONSTRAINT "FK_95c8a0c593c2320addcc7af1468" FOREIGN KEY ("sharedById") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "post_shares" ADD CONSTRAINT "FK_15ea4c725c1f17facbc53b75e53" FOREIGN KEY ("originalPostId") REFERENCES "posts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "post_saves" ADD CONSTRAINT "FK_15b357815f5e6a765e60ee0e32e" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "post_saves" ADD CONSTRAINT "FK_08107d1d38fc71d50702e1a8733" FOREIGN KEY ("postId") REFERENCES "posts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "follows" ADD CONSTRAINT "FK_fdb91868b03a2040db408a53331" FOREIGN KEY ("followerId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "follows" ADD CONSTRAINT "FK_666a44940ce8279976767c6b5e3" FOREIGN KEY ("followeeId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "posts" ADD CONSTRAINT "FK_c5a322ad12a7bf95460c958e80e" FOREIGN KEY ("authorId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reports" ADD CONSTRAINT "FK_4353be8309ce86650def2f8572d" FOREIGN KEY ("reporterId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "post_likes" ADD CONSTRAINT "FK_6999d13aca25e33515210abaf16" FOREIGN KEY ("postId") REFERENCES "posts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "post_likes" ADD CONSTRAINT "FK_37d337ad54b1aa6b9a44415a498" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "post_comments" ADD CONSTRAINT "FK_ac65d744abc05279aee0b290857" FOREIGN KEY ("postId") REFERENCES "posts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "post_comments" ADD CONSTRAINT "FK_2b93091c2f4d6c9cf7c9b32e29f" FOREIGN KEY ("authorId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_ratings" ADD CONSTRAINT "FK_7f190f97558c87ec1c14a3d6378" FOREIGN KEY ("buyer_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_ratings" ADD CONSTRAINT "FK_538c9489e98d4874e8db0c4cafd" FOREIGN KEY ("product_id") REFERENCES "shop_products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_disputes" ADD CONSTRAINT "fk_order_disputes_resolved_by_id" FOREIGN KEY ("resolved_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_disputes" ADD CONSTRAINT "FK_77f99ec8e32921d9c29a468c4b6" FOREIGN KEY ("resolvedById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_settings" ADD CONSTRAINT "FK_user_settings_userId" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
